// AUTO-GENERATED by scripts/utils/generate-tool-map.ts - do not edit
// zod import intentionally omitted (auto-generated file)

import type * as Mod0 from "@/tools/database/clear-all-data";
import type * as Mod1 from "@/tools/database";
import type * as Mod2 from "@/tools/database/query-data";
import type * as Mod3 from "@/tools/development/getDatabaseSchema";
import type * as Mod4 from "@/tools/development/getDatabaseTypes";
import type * as Mod5 from "@/tools/development";
import type * as Mod6 from "@/tools/scraper";
import type * as Mod7 from "@/tools/scraper/scrape";
import type * as Mod8 from "@/tools/tasks/cancel";
import type * as Mod9 from "@/tools/tasks/get";
import type * as Mod10 from "@/tools/tasks";
import type * as Mod11 from "@/tools/tasks/list";
import type * as Mod12 from "@/tools/tasks/result";
import type * as Mod13 from "@/tools/tasks/tail";
import type * as Mod14 from "@/tools/tasks/test";

export type ToolMap = {
  "@/tools/database/clear-all-data": {
    clearAllDataTool: {
      input: Parameters<typeof Mod0.clearAllDataTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod0.clearAllDataTool.handler>>;
      handler: typeof Mod0.clearAllDataTool.handler;
    };
  };
  "@/tools/database": {
    clearAllDataTool: {
      input: Parameters<typeof Mod1.clearAllDataTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod1.clearAllDataTool.handler>>;
      handler: typeof Mod1.clearAllDataTool.handler;
    };
    queryDataTool: {
      input: Parameters<typeof Mod1.queryDataTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod1.queryDataTool.handler>>;
      handler: typeof Mod1.queryDataTool.handler;
    };
  };
  "@/tools/database/query-data": {
    queryDataTool: {
      input: Parameters<typeof Mod2.queryDataTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod2.queryDataTool.handler>>;
      handler: typeof Mod2.queryDataTool.handler;
    };
  };
  "@/tools/development/getDatabaseSchema": {
    getDatabaseSchemaTool: {
      input: Parameters<typeof Mod3.getDatabaseSchemaTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod3.getDatabaseSchemaTool.handler>>;
      handler: typeof Mod3.getDatabaseSchemaTool.handler;
    };
  };
  "@/tools/development/getDatabaseTypes": {
    getDatabaseTypesTool: {
      input: Parameters<typeof Mod4.getDatabaseTypesTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod4.getDatabaseTypesTool.handler>>;
      handler: typeof Mod4.getDatabaseTypesTool.handler;
    };
  };
  "@/tools/development": {
    getDatabaseSchemaTool: {
      input: Parameters<typeof Mod5.getDatabaseSchemaTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod5.getDatabaseSchemaTool.handler>>;
      handler: typeof Mod5.getDatabaseSchemaTool.handler;
    };
    getDatabaseTypesTool: {
      input: Parameters<typeof Mod5.getDatabaseTypesTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod5.getDatabaseTypesTool.handler>>;
      handler: typeof Mod5.getDatabaseTypesTool.handler;
    };
  };
  "@/tools/scraper": {
    scrapeTool: {
      input: Parameters<typeof Mod6.scrapeTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod6.scrapeTool.handler>>;
      handler: typeof Mod6.scrapeTool.handler;
    };
  };
  "@/tools/scraper/scrape": {
    scrapeTool: {
      input: Parameters<typeof Mod7.scrapeTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod7.scrapeTool.handler>>;
      handler: typeof Mod7.scrapeTool.handler;
    };
  };
  "@/tools/tasks/cancel": {
    tasksCancelTool: {
      input: Parameters<typeof Mod8.tasksCancelTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod8.tasksCancelTool.handler>>;
      handler: typeof Mod8.tasksCancelTool.handler;
    };
  };
  "@/tools/tasks/get": {
    tasksGetTool: {
      input: Parameters<typeof Mod9.tasksGetTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod9.tasksGetTool.handler>>;
      handler: typeof Mod9.tasksGetTool.handler;
    };
  };
  "@/tools/tasks": {
    tasksCancelTool: {
      input: Parameters<typeof Mod10.tasksCancelTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod10.tasksCancelTool.handler>>;
      handler: typeof Mod10.tasksCancelTool.handler;
    };
    tasksGetTool: {
      input: Parameters<typeof Mod10.tasksGetTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod10.tasksGetTool.handler>>;
      handler: typeof Mod10.tasksGetTool.handler;
    };
    tasksListTool: {
      input: Parameters<typeof Mod10.tasksListTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod10.tasksListTool.handler>>;
      handler: typeof Mod10.tasksListTool.handler;
    };
    tasksResultTool: {
      input: Parameters<typeof Mod10.tasksResultTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod10.tasksResultTool.handler>>;
      handler: typeof Mod10.tasksResultTool.handler;
    };
    tasksTailTool: {
      input: Parameters<typeof Mod10.tasksTailTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod10.tasksTailTool.handler>>;
      handler: typeof Mod10.tasksTailTool.handler;
    };
    testTaskTool: {
      input: Parameters<typeof Mod10.testTaskTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod10.testTaskTool.handler>>;
      handler: typeof Mod10.testTaskTool.handler;
    };
  };
  "@/tools/tasks/list": {
    tasksListTool: {
      input: Parameters<typeof Mod11.tasksListTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod11.tasksListTool.handler>>;
      handler: typeof Mod11.tasksListTool.handler;
    };
  };
  "@/tools/tasks/result": {
    tasksResultTool: {
      input: Parameters<typeof Mod12.tasksResultTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod12.tasksResultTool.handler>>;
      handler: typeof Mod12.tasksResultTool.handler;
    };
  };
  "@/tools/tasks/tail": {
    tasksTailTool: {
      input: Parameters<typeof Mod13.tasksTailTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod13.tasksTailTool.handler>>;
      handler: typeof Mod13.tasksTailTool.handler;
    };
  };
  "@/tools/tasks/test": {
    testTaskTool: {
      input: Parameters<typeof Mod14.testTaskTool.handler>[0];
      output: Awaited<ReturnType<typeof Mod14.testTaskTool.handler>>;
      handler: typeof Mod14.testTaskTool.handler;
    };
  };
};

export type KnownModule = keyof ToolMap;
export type KnownExport<M extends KnownModule> = keyof ToolMap[M] & string;
